#! /bin/bash

########################################
#                                      #
# Simple script to remove stray files  #
#        generated by LaTeX.           #
#         Use with caution!            #
#                                      #
########################################

mv example.tex example-backup.tex

tex_files=(./example.*)
if [ -e ${tex_files[0]} ];
    then
    rm example.*
fi

mv example-backup.tex example.tex